<a href="https://colab.research.google.com/github/faseenafarz/machine-learning/blob/main/credit_score_classification_naiyebayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
#Import the libraries
import numpy as np #Linear algebra
import pandas as pd # data analysis and manipulation eg:reading the dataset(read_csv)
#Reading the dataset
df=pd.read_csv('/content/Credit Score Classification Dataset (1).csv')
df

Age  Gender    Income            Education Marital Status  \
0     25  Female   50000.0    Bachelor's Degree         Single   
1     30    Male  100000.0      Master's Degree        Married   
2     35  Female   75000.0            Doctorate        Married   
3     40    Male  125000.0  High School Diploma         Single   
4     45  Female  100000.0    Bachelor's Degree        Married   
..   ...     ...       ...                  ...            ...   
159   29  Female   27500.0  High School Diploma         Single   
160   34    Male   47500.0   Associate's Degree         Single   
161   39  Female   62500.0    Bachelor's Degree        Married   
162   44    Male   87500.0      Master's Degree         Single   
163   49  Female   77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
0                     0         Rented         High  
1                     2          Owned         High  
2                     1          Owned         High  
3                     0          Owned         High  
4                     3          Owned         High  
..                  ...            ...          ...  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High  

[164 rows x 8 columns]

In [6]:
#Displaying the first rows of dataset
df.head()

Age  Gender    Income            Education Marital Status  \
0   25  Female   50000.0    Bachelor's Degree         Single   
1   30    Male  100000.0      Master's Degree        Married   
2   35  Female   75000.0            Doctorate        Married   
3   40    Male  125000.0  High School Diploma         Single   
4   45  Female  100000.0    Bachelor's Degree        Married   

   Number of Children Home Ownership Credit Score  
0                   0         Rented         High  
1                   2          Owned         High  
2                   1          Owned         High  
3                   0          Owned         High  
4                   3          Owned         High

In [7]:
#Displaying the last rows of dataset
df.tail()

Age  Gender   Income            Education Marital Status  \
159   29  Female  27500.0  High School Diploma         Single   
160   34    Male  47500.0   Associate's Degree         Single   
161   39  Female  62500.0    Bachelor's Degree        Married   
162   44    Male  87500.0      Master's Degree         Single   
163   49  Female  77500.0            Doctorate        Married   

     Number of Children Home Ownership Credit Score  
159                   0         Rented          Low  
160                   0         Rented      Average  
161                   2          Owned         High  
162                   0          Owned         High  
163                   1          Owned         High

In [8]:
#Checking the datatypes
df.dtypes

Age                     int64
Gender                 object
Income                float64
Education              object
Marital Status         object
Number of Children      int64
Home Ownership         object
Credit Score           object
dtype: object

In [9]:
#Checking the null values
df.isna().sum()

Age                   0
Gender                6
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [10]:
g=df['Gender'].mode()[0]
g

'Female'

In [11]:
df['Gender'].fillna(g,inplace=True)
i=df['Income'].mean()
df['Income'].fillna(i,inplace=True)

In [12]:
df.isna().sum()

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [13]:
#Encoding
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender']=lab.fit_transform(df['Gender'])



In [14]:
df['Education']=lab.fit_transform(df['Education'])


In [15]:
df['Marital Status']=lab.fit_transform(df['Marital Status'])


In [16]:
df['Home Ownership']=lab.fit_transform(df['Home Ownership'])
df

Age  Gender    Income  Education  Marital Status  Number of Children  \
0     25       0   50000.0          1               1                   0   
1     30       1  100000.0          4               0                   2   
2     35       0   75000.0          2               0                   1   
3     40       1  125000.0          3               1                   0   
4     45       0  100000.0          1               0                   3   
..   ...     ...       ...        ...             ...                 ...   
159   29       0   27500.0          3               1                   0   
160   34       1   47500.0          0               1                   0   
161   39       0   62500.0          1               0                   2   
162   44       1   87500.0          4               1                   0   
163   49       0   77500.0          2               0                   1   

     Home Ownership Credit Score  
0                 1         High  
1                 0         High  
2                 0         High  
3                 0         High  
4                 0         High  
..              ...          ...  
159               1          Low  
160               1      Average  
161               0         High  
162               0         High  
163               0         High  

[164 rows x 8 columns]

In [17]:
x=df.iloc[:,:-1].values
x

array([[2.50e+01, 0.00e+00, 5.00e+04, ..., 1.00e+00, 0.00e+00, 1.00e+00],
       [3.00e+01, 1.00e+00, 1.00e+05, ..., 0.00e+00, 2.00e+00, 0.00e+00],
       [3.50e+01, 0.00e+00, 7.50e+04, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       ...,
       [3.90e+01, 0.00e+00, 6.25e+04, ..., 0.00e+00, 2.00e+00, 0.00e+00],
       [4.40e+01, 1.00e+00, 8.75e+04, ..., 1.00e+00, 0.00e+00, 0.00e+00],
       [4.90e+01, 0.00e+00, 7.75e+04, ..., 0.00e+00, 1.00e+00, 0.00e+00]])

In [18]:
y=df.iloc[:,-1].values
y

array(['High', 'High', 'High', 'High', 'High', 'High', 'Average',
       'Average', 'High', 'High', 'High', 'High', 'Low', 'Average',
       'High', 'High', 'High', 'High', 'Low', 'Average', 'High', 'High',
       'High', 'High', 'Low', 'Average', 'High', 'High', 'High',
       'Average', 'High', 'High', 'High', 'High', 'High', 'Average',
       'Average', 'High', 'High', 'High', 'High', 'Low', 'Average',
       'High', 'High', 'High', 'High', 'Low', 'Average', 'High', 'High',
       'High', 'High', 'Low', 'Average', 'High', 'High', 'High',
       'Average', 'High', 'High', 'Average', 'High', 'High', 'High',
       'High', 'High', 'Average', 'Average', 'High', 'High', 'High',
       'High', 'Low', 'Average', 'High', 'High', 'High', 'High', 'Low',
       'Average', 'High', 'High', 'High', 'High', 'Low', 'Average',
       'High', 'High', 'High', 'Average', 'High', 'High', 'Average',
       'High', 'High', 'High', 'High', 'High', 'Average', 'Average',
       'High', 'High', 'High', 'High'

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)
x_train

array([[4.50000000e+01, 0.00000000e+00, 1.15000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [5.10000000e+01, 1.00000000e+00, 1.35000000e+05, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.50000000e+01, 0.00000000e+00, 1.10000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 4.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 4.00000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 7.50000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.20000000e+01, 1.00000000e+00, 1.05000000e+05, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 6.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0

In [20]:
x_test

array([[2.50000000e+01, 0.00000000e+00, 5.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.39516129e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 5.50000000e+04, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 6.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 9.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 5.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.25000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.25000000e+04, 2.00000000e+00,
        0.00000000e+00, 1

In [21]:
y_train

array(['High', 'High', 'High', 'Average', 'Average', 'High', 'High',
       'Average', 'High', 'Low', 'High', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'Low', 'High', 'Average', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'Low', 'High', 'Average', 'High', 'Low', 'High',
       'Low', 'High', 'Average', 'Low', 'High', 'Average', 'High',
       'Average', 'High', 'High', 'Average', 'High', 'Low', 'High',
       'Average', 'High', 'High', 'High', 'Average', 'Average', 'High',
       'High', 'High', 'Average', 'High', 'High', 'Average', 'High',
       'High', 'High', 'Low', 'Average', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'Average', 'High', 'High', 'High', 'Average',
       'Average', 'High', 'High', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'High', 'High', 'High', 'Average',
       'High', 'H

In [22]:
y_test

array(['Average', 'High', 'Average', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'Average', 'Low', 'High', 'High', 'Low',
       'High', 'High', 'Low', 'High', 'High', 'High', 'Low', 'Low',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'Low', 'High', 'Average', 'Low', 'Average', 'Average', 'Average',
       'High', 'High', 'High', 'Average'], dtype=object)

In [23]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.77593283, -1.01770049,  0.94515333, -0.73865505, -0.98260737,
         2.66391337, -0.66561098],
       [ 1.49704432,  0.98260737,  1.59465735, -0.73865505, -0.98260737,
        -0.69792564, -0.66561098],
       [ 0.77593283, -1.01770049,  0.78277732, -0.73865505, -0.98260737,
         2.66391337, -0.66561098],
       [-0.5461049 ,  0.98260737, -1.24692275, -1.45227095,  1.01770049,
        -0.69792564,  1.50237907],
       [-1.50758688, -1.01770049, -1.49048675, -1.45227095,  1.01770049,
        -0.69792564,  1.50237907],
       [ 0.65574758,  0.98260737, -0.35385472,  1.40219264,  1.01770049,
        -0.69792564, -0.66561098],
       [ 0.41537709,  0.98260737,  0.62040132,  1.40219264,  1.01770049,
        -0.69792564, -0.66561098],
       [-0.90666064,  0.98260737, -0.67860673, -0.73865505,  1.01770049,
        -0.69792564,  1.50237907],
       [ 0.29519184,  0.98260737,  0.78277732, -0.02503915,  1.01770049,
        -0.69792564, -0.66561098],
       [-1.38740164, -1.0177

In [24]:
x_test

array([[-1.62777213, -1.01770049, -1.00335874, -0.73865505,  1.01770049,
        -0.69792564,  1.50237907],
       [ 1.13648857, -1.01770049, -0.06314929, -0.02503915, -0.98260737,
         0.42268736, -0.66561098],
       [-1.50758688, -1.01770049, -1.00335874, -0.73865505, -0.98260737,
         0.42268736, -0.66561098],
       [ 0.05482134, -1.01770049, -0.75979473, -0.73865505, -0.98260737,
         1.54330037, -0.66561098],
       [-0.42591965, -1.01770049,  0.1332733 , -0.02503915, -0.98260737,
         0.42268736, -0.66561098],
       [-1.62777213, -1.01770049, -1.00335874, -0.73865505,  1.01770049,
        -0.69792564,  1.50237907],
       [ 1.13648857, -1.01770049, -0.11029071, -0.02503915, -0.98260737,
         0.42268736, -0.66561098],
       [ 1.13648857, -1.01770049, -0.11029071, -0.02503915, -0.98260737,
         0.42268736, -0.66561098],
       [-0.3057344 , -1.01770049,  0.29564931,  1.40219264, -0.98260737,
         1.54330037, -0.66561098],
       [ 0.89611808, -1.0177

In [25]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
y_pred

array(['Low', 'High', 'High', 'High', 'High', 'Low', 'High', 'High',
       'High', 'High', 'Average', 'Low', 'High', 'High', 'Low', 'High',
       'Average', 'Low', 'High', 'High', 'High', 'Low', 'Low', 'High',
       'High', 'High', 'High', 'High', 'High', 'Average', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'Average', 'High', 'Low',
       'High', 'Low', 'Low', 'Low', 'High', 'Average', 'High', 'High',
       'High', 'Low'], dtype='<U7')

In [26]:
from sklearn.metrics import confusion_matrix
mat=confusion_matrix(y_test,y_pred)
print(mat)

[[ 4  2  5]
 [ 1 31  0]
 [ 0  0  7]]


In [27]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.84