<a href="https://colab.research.google.com/github/faseenafarz/machine-learning/blob/main/frozen_lake_using_RL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [ ]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:

num_episodes =20000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
      # Exploration-exploitation trade-off
       exploration_rate_threshold = random.uniform(0, 1)
       if exploration_rate_threshold > exploration_rate:
           action = np.argmax(q_table[state,:])
       else:
           action = env.action_space.sample()
       new_state, reward, done, info = env.step(action)

       q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
       learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

       state = new_state
       rewards_current_episode += reward

       if done == True:
          break

    exploration_rate = min_exploration_rate + \
       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)


rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000



/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


********Average reward per thousand episodes********

1000 :  0.04500000000000003
2000 :  0.20500000000000015
3000 :  0.4140000000000003
4000 :  0.5230000000000004
5000 :  0.5980000000000004
6000 :  0.6590000000000005
7000 :  0.6750000000000005
8000 :  0.6660000000000005
9000 :  0.6830000000000005
10000 :  0.6550000000000005
11000 :  0.6810000000000005
12000 :  0.6850000000000005
13000 :  0.6800000000000005
14000 :  0.6900000000000005
15000 :  0.6830000000000005
16000 :  0.6970000000000005
17000 :  0.6740000000000005
18000 :  0.6470000000000005
19000 :  0.6840000000000005
20000 :  0.6630000000000005


In [ ]:
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.53468912 0.48163072 0.48044037 0.47497567]
 [0.34703578 0.30377798 0.21843754 0.4061254 ]
 [0.3379793  0.27644686 0.27580332 0.25707262]
 [0.05296371 0.13433808 0.04232922 0.06652103]
 [0.55026364 0.38261244 0.31425888 0.4293287 ]
 [0.         0.         0.         0.        ]
 [0.1158252  0.08668613 0.21930039 0.13053169]
 [0.         0.         0.         0.        ]
 [0.34790388 0.36237715 0.39490691 0.56843952]
 [0.46646929 0.57652336 0.34895425 0.34897296]
 [0.50321387 0.33781034 0.29818905 0.3536165 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48276888 0.46417191 0.7375791  0.45607485]
 [0.72962063 0.8895863  0.7178632  0.73033907]
 [0.         0.         0.         0.        ]]


In [ ]:

for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):
       clear_output(wait=True)
       print(env.render())
       time.sleep(0.3)

       action = np.argmax(q_table[state,:])
       new_state, reward, done, info = env.step(action)


       if done:
          clear_output(wait=True)
          env.render()
          if reward == 1:
             print("****You reached the goal!****")
             time.sleep(3)
          else:
             print("****You fell through a hole!****")
             time.sleep(3)
          clear_output(wait=True)
          break
       state = new_state
env.close()



****You reached the goal!****


In [ ]:
!pip install gymnasium

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 9.4 MB/s eta 0:00:00
